; Problem 2.
; Each new term in the Fibonacci sequence is generated by adding the previous two terms.
; By starting with 1 and 2, the first 10 terms will be:
;
; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;
; By considering the terms in the Fibonacci sequence whose values do not exceed four million,
; find the sum of the even-valued terms.

(ns p-2)
(defn fib []
  (do (def prev 0) (def tmp 0) (def sum 0))
  (loop [curr 1]
    (when (< curr 4000000)
      (def tmp prev)
      (def prev curr)
      (when (= (rem curr 2) 0) (def sum (+ sum curr)))
      (recur (+ curr tmp))
      ))
  (println sum))

(defn main
(fib))
